version: "3"

services:
    postgres:
        image: "postgres:latest"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    app:
        build: .
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
